@startwbs
!theme plain
* 小型对战游戏软件开发项目
** 制定项目计划
*** 初步调研
*** 范围计划
*** 进度计划
*** 成本计划
** 系统分析
*** 竞品分析
*** 游戏玩法需求分析
*** 游戏系统需求分析
*** 游戏网络功能需求分析
*** 分析报告终稿
*** 需求确认
** 系统设计
*** 系统架构设计
*** 网络结构设计
*** 系统总体设计
*** 子系统详细设计
**** 对局系统详细设计
**** 联机系统详细设计
*** 设计报告终稿
*** 设计报告评审
** 系统实施
*** 对局系统实施
*** 联机系统实施
*** 系统测试
*** 系统发布
** 系统交付
*** 用户功能测试
*** 用户性能测试
@endwbs